project := "x_engine"
import "../common.just"

trace-size := "134217728" # 128 MiB

benchmark-cflags := "-std=c++23 -O3 -Wall"

# list just recipes
default:
    just -l

# run without tracing
run: xclbin
    python3 run.py --xclbin build/{{project}}.xclbin --instr build/{{project}}_insts.bin -k MLIR_AIE

# run with tracing and process trace
trace: (xclbin trace-size)
    rm -f build/trace.txt
    python3 run.py --xclbin build/{{project}}.xclbin --instr build/{{project}}_insts.bin -k MLIR_AIE \
        -t {{trace-size}} --trace-file build/trace.txt
    just _process_trace

# run C++ benchmark
benchmark: xclbin
	g++ {{benchmark-cflags}} -I/opt/xilinx/xrt/include -I{{mlir-aie-dir}}/runtime_lib/x86_64/test_lib/include -o build/benchmark.o -c benchmark.cc
	g++ {{benchmark-cflags}} -o build/benchmark -L/opt/xilinx/xrt/lib -Wl,-rpath,/opt/xilinx/xrt/lib -lxrt_coreutil build/benchmark.o {{mlir-aie-dir}}/runtime_lib/x86_64/test_lib/lib/libtest_utils.a
	./build/benchmark

# generate MLIR
mlir trace="0": _build_dir
    python3 {{project}}.py --trace-size {{trace}} > build/{{project}}.mlir

# build .xclbin
xclbin trace="0": (mlir trace) kernel _aiecc

# test
test: xclbin
    pytest

# memory throughput benchmark
memory-benchmark *args:
    python3 ingest_throughput_benchmark.py {{args}}
