project := "peak_tops"
import "../common.just"

trace-size := "131072"
trace-compute-tiles := "16"
compute-tiles := "32"
trace-compute-per-column := "2"
compute-per-column := "4"
trace-iterations := "1024"
iterations := "4194304"

# list just recipes
default:
    just -l

# run without tracing
run: xclbin
    python3 run.py --xclbin build/{{project}}.xclbin --instr build/{{project}}_insts.bin -k MLIR_AIE \
        --compute-tiles {{compute-tiles}} --iterations {{iterations}}

# run with tracing and process trace
trace: (xclbin trace-size trace-compute-tiles trace-compute-per-column trace-iterations)
    rm -f build/trace.txt
    python3 run.py --xclbin build/{{project}}.xclbin --instr build/{{project}}_insts.bin -k MLIR_AIE \
        --compute-tiles {{trace-compute-tiles}} --iterations {{trace-iterations}} \
        -t {{trace-size}} --trace-file build/trace.txt
    just _process_trace

# generate MLIR
mlir trace="0" compute-tiles=compute-tiles compute-per-column=compute-per-column iterations=iterations: _build_dir
    python3 {{project}}.py \
        --trace-size {{trace}} --compute-tiles {{compute-tiles}} \
        --compute-per-column {{compute-per-column}} --iterations {{iterations}} > build/{{project}}.mlir

# build .xclbin
xclbin trace="0" compute-tiles=compute-tiles compute-per-column=compute-per-column iterations=iterations: (mlir trace compute-tiles compute-per-column iterations) kernel _aiecc
